

inputs:
  # Notice principal
  notice: 'data/SemSac_notices.xlsx'
  # Catalogue des personnes physiques
  personphysique: 'data/catalogues/SemSac_personnes_physiques.xlsx'
  # Lieux
  lieux_Geocode: 'data/catalogues/SemSac_lieux_total_geocode.xlsx'
  
  
  # Catalogue des personnes morales
  personnesmorales: 'data/catalogues/SemSac_personnes_morales.xlsx'
  # Catalogue des juridictions
  juridiction: 'data/catalogues/SemSac_juridictions.xlsx'
  # 
  arkCode: 'data/catalogues/SemSac_ark.xlsx'
  
  #
template:
  conf_notice: 'data/templateJSON/notices.json'

vocabularies:
  voc_typeProfession: 'data/vocabularies/typeProfession.json'
  voc_sexePersonnes: 'data/vocabularies/sexePersonnes.json'
  voc_typeJuridiction: 'data/vocabularies/typeJuridiction.json'
  voc_typeLieu: 'data/vocabularies/typeLieu.json'
  voc_typeProcedure: 'data/vocabularies/typeProcedure.json'
  voc_qualifFaits: 'data/vocabularies/qualifFaits.json'
  voc_collectivite: 'data/vocabularies/typeCollectivit√©.json'

output:
  lieux: "output/lieux"
  notices: "output/notices"